version: "3.8"
services:
  postgres:
    image: postgres:16.1
    container_name: postgres_test
    environment:
      POSTGRES_DB: "main_database"
      POSTGRES_USER: "leonid"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - leonid_network
    
  postgres_server:
    build:
      context: .
      dockerfile: Postgres_server
    container_name: postgres_server
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - leonid_network

networks:
  leonid_network:
    driver: bridge