environment_mode: "dev" # Среда работы - на локальной машине, доступны ("local", "prodaction")
http_server:
  page_path: ./resources/index.html
  address: ":8082" # Адрес сервера
  request_timeout: 4s # Таймаут запроса
  connection_timeout: 60s # Таймаут соединения